name: Build and Push on Dockerhub

on:
  push:
    branches-ignore:
      - main

  
  workflow_dispatch:
    branches-ignore:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU for building
        uses: actions/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_PASSWORD }}'
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: '${{ github.ref_name }}'
          push: true
          tags: 'agdon01/dev_environments:${{ github.ref_name }}'